# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stage2.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Installer(object):
    def setupUi(self, Installer):
        Installer.setObjectName("Installer")
        Installer.resize(520, 60)
        self.ProgressBar = QtWidgets.QProgressBar(Installer)
        self.ProgressBar.setGeometry(QtCore.QRect(0, 20, 521, 31))
        self.ProgressBar.setProperty("value", 24)
        self.ProgressBar.setObjectName("ProgressBar")

        self.retranslateUi(Installer)
        QtCore.QMetaObject.connectSlotsByName(Installer)

    def retranslateUi(self, Installer):
        _translate = QtCore.QCoreApplication.translate
        Installer.setWindowTitle(_translate("Installer", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Installer = QtWidgets.QDialog()
    ui = Ui_Installer()
    ui.setupUi(Installer)
    Installer.show()
    sys.exit(app.exec_())
